// Package resume renders an ATS-friendly PDF from the portfolio content. It is
// deliberately a pure function of Data: no database, no AWS, no HTTP. That keeps
// the layout testable and makes the generated bytes reproducible.
//
// The output obeys two hard constraints from the Job Search Playbook guidance:
//  1. single column, no sidebars, no icons, no graphics
//  2. strictly ASCII text, because the PDF core fonts are encoded in CP1252 while
//     fpdf writes string bytes verbatim, so any non-ASCII rune would be emitted
//     as mojibake and would then be copied into the ATS as garbage
package resume

// Data is everything the template renders. It mirrors the portfolio tables but
// carries no identifiers or ordering fields, because a resume needs neither.
type Data struct {
	Profile    Profile
	Skills     []SkillGroup
	Experience []Experience
	Projects   []Project
	Education  []Education
	Extras     []ExtraGroup
}

// Profile holds the header block. Contact details are rendered in the body flow
// rather than a PDF page header, because parsers handle page headers poorly.
type Profile struct {
	FullName  string
	Title     string
	Summary   string
	Email     string
	Phone     string
	Location  string
	LinkedIn  string
	Github    string
	Portfolio string
	Twitter   string
}

// SkillGroup is one category with its skills.
type SkillGroup struct {
	Category string
	Skills   []string
}

// Experience is one role with its bullets.
type Experience struct {
	Company    string
	Role       string
	Location   string
	StartDate  string
	EndDate    string
	IsCurrent  bool
	Bullets    []string
}

// Project is one showcase project with its bullets.
type Project struct {
	Title        string
	Role         string
	Technologies []string
	RepoURL      string
	LiveURL      string
	StartDate    string
	EndDate      string
	IsCurrent    bool
	Description  string
	Bullets      []string
}

// Education is one degree.
type Education struct {
	Institution  string
	Degree       string
	FieldOfStudy string
	StartYear    int
	EndYear      int
	IsCurrent    bool
	GPA          string
	Honors       string
}

// ExtraGroup is one extras category with its entries.
type ExtraGroup struct {
	Category string
	Entries  []Extra
}

// Extra is one certification, award or similar highlight.
type Extra struct {
	Title      string
	Issuer     string
	IssuedDate string
}
